openapi: 3.0.3
info:
  title: Currency prediction API
  version: 1.0.0
  description: API that predicts currency
paths:
  /api:
    get:
      operationId: api_retrieve
      description: Currency prediction for certain interval
      parameters:
      - in: query
        name: api_key
        schema:
          type: string
        description: API key for authentication
        required: true
      - in: query
        name: end_date
        schema:
          type: string
          format: date
        description: date by which the prediction interval ends
        required: true
      - in: query
        name: start_date
        schema:
          type: string
          format: date
        description: date by which the prediction interval starts
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrencyPrediction'
              examples:
                Example1:
                  value:
                    status: ok
                    result_message: plot_0.png
                  summary: Response code is 200, programme maintained the request
                  description: Everything is fine
                Example2:
                  value:
                    status: error
                    result_message: Неверный формат данных! Дата должна отображаться
                      в виде дд-мм-гггг!
                  summary: Response code is 200, programme maintained the request
                  description: Error occurred (parameters format or value is wrong)
          description: ''
components:
  schemas:
    CurrencyPrediction:
      type: object
      properties:
        status:
          type: string
        result_message:
          type: string
      required:
      - result_message
      - status
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
